language: java

jdk:
  - openjdk8

# To increase the memory size available during Travis build.
sudo: required

env:
  global:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    # Encrypted `GCS_SECRET` variable.
    - secure: "aSu4WatRfyjgkt3GIhEIbsfsXmdaPppXuAD6NeO2qwr/dG/JXQh/GImJT8wXz5jrQiUL7UldimICiVwEpgl4p6hmbyAbCII7YnMjOWv+rGdKSnod/xsz5iWqlncY3dIzv+sZ7ZvkmjNzMlxvcp8t3eTlxA7LZxO07hCALh+uE9JjdFnj4Xxtm53SAJvnsvbhp/f+W6iEo4nQO0V6cn2LokpmL/E9cl0varztGRNcv/r+EgAuRFPFZO92/tFv8o2d+QNuitJfqRAi7lzTNC7/nPWBx5U0TgCnRCxVm0i3+aRGRw6JZPTgTV95gXVgb11b/aOn1WF0+ocjuC/p5HGB0bBAIADtFY5ud+9tgAlFvFrxn0g/O5qMM3URugXuUAgK31tyGuxtAbG/AU5bebfRiJcYYWiJVNCouJTGlM+WbxHXFO+1ZiSmxHKAHit2nTeeYqPDUGmnCHcDqRvn9CydRMd8bJJ0Htl8try99KQ0dPOVx+Tm8M2M2idfSbYbXe2kM6Cm1IiZWsZJ4vtRHK2XARSM06l7Ptpls1Xi6FWwxmU46hSQ1lVV8s4Bc6Kk8Cnq80rFSKnwXbZKQksOUdLyZpalTXMSMivxBR14PEUK33ZXfO5Ei6GXY6puxfrjmi9Lp0ehehbfElSCANQAmYCbjHgcwvmQICEFUEG2dz4hjLc="
    # Encrypted `NPM_TOKEN` variable to enable JS publishing.
    - secure: "noIW4zt8jp2S1C6Sg89PQJPLsRaVBJCYybQ/C5e/Gnb5dvBbtdTidFY7nWDA9gzw/D6o1kDpwTjWcvWF7m80AFMKuE4l4ikceR6bFmSWHnd9yy92iPcd1vioCpP2BniKh9FHwHTRtNB74Oyle7FCpoPWk/AU9y/sz7YzHk4YTbPPmuv8nInnztbHY2Ykjsuw5B/EsmBuAA465RFyb9oaU3Z+P/qX5rMKuZvvy02BYB+zr0MeFNOBE70MHqQ0Eq9DDqYlfm8PtK1ULVVPsA5b11fqc5gYnigv/baBHpCN/SrkK2vs2eRnIXn9j9+7XMqSi+vcDKPi+hiAa39iLWRB+88c8o+fCI5Z+YNmDiCKGh7dedt4gbMqgqz4dvlu0IhxmksdQFVTU1fkqbXgz+4xliiFFMMYVD+0ZJmULDwcJBAB+WJHI/vRVzS6Db4NrewoLZFxjYSUF8Nd4GxekWe507TlMcbRXJDqZxQVrdbSWooYr+zbzDP64e16tnF1D5ZXAw7Cw/vVS9hkWi3gWYU/P5zZjLg7OjXTF4QCQ4588lz57HdBst3HuufG1lUcm6PZbimHNcpqaPfu5PBHA5Sgp+KYhnlCmBJw2g3QcIv0YEwYnkKbMykJ/hQcl0cOXAeNx40zMxn2BmH7Up6Df4SxqhgxA3N9I4pynZB2ErX7dUo="
before_install:
  - chmod +x gradlew

script:
  - ./gradlew check --stacktrace

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_6b205086b541_key -iv $encrypted_6b205086b541_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - chmod +x ./config/scripts/upload-artifacts.sh
  - ./config/scripts/upload-artifacts.sh
